import React from 'react';
import { Box, Typography, Divider, Container } from '@mui/material';
import Header from '../components/header';
import Footer from '../components/footer';

const Terms = () => {
  return (
    <>
      <Header />
      <Box sx={{ py: 8, px: 2, backgroundColor: '#f9fbfd', minHeight: '100vh' }}>
        <Container maxWidth="md">
          <Typography variant="h3" fontWeight="bold" gutterBottom align="center">
            Terms of Service
          </Typography>
          <Typography variant="subtitle1" color="text.secondary" align="center" mb={4}>
            Last updated: June 23, 2025
          </Typography>

          <Divider sx={{ my: 4 }} />

          <Typography variant="h5" fontWeight="bold" gutterBottom>
            1. Acceptance of Terms
          </Typography>
          <Typography variant="body1" paragraph>
            By accessing or using NeuraMedix, you agree to be bound by these Terms of Service and our Privacy Policy.
            If you do not agree, do not use our services.
          </Typography>

          <Typography variant="h5" fontWeight="bold" gutterBottom>
            2. Services
          </Typography>
          <Typography variant="body1" paragraph>
            NeuraMedix provides AI-powered tools for biomedical research, including but not limited to:
            molecule binding prediction, tumor detection, and research paper analysis.
            These tools are intended for research and educational purposes only.
          </Typography>

          <Typography variant="h5" fontWeight="bold" gutterBottom>
            3. User Responsibilities
          </Typography>
          <Typography variant="body1" paragraph>
            You are responsible for ensuring that your use of our tools complies with all applicable laws and ethical
            standards. Do not use our platform for illegal, clinical, or diagnostic purposes.
          </Typography>

          <Typography variant="h5" fontWeight="bold" gutterBottom>
            4. Intellectual Property
          </Typography>
          <Typography variant="body1" paragraph>
            All content, models, and code on NeuraMedix are the property of NeuraMedix or its licensors. You may not
            reproduce, distribute, or resell any part of the platform without prior written consent.
          </Typography>

          <Typography variant="h5" fontWeight="bold" gutterBottom>
            5. Account & Access
          </Typography>
          <Typography variant="body1" paragraph>
            You may need to create an account to access certain features. You are responsible for safeguarding your
            login credentials and for any activity under your account.
          </Typography>

          <Typography variant="h5" fontWeight="bold" gutterBottom>
            6. Limitation of Liability
          </Typography>
          <Typography variant="body1" paragraph>
            NeuraMedix is provided “as is” without warranties. We are not liable for any direct or indirect damages
            arising from your use of our services or reliance on outputs generated by our AI tools.
          </Typography>

          <Typography variant="h5" fontWeight="bold" gutterBottom>
            7. Termination
          </Typography>
          <Typography variant="body1" paragraph>
            We reserve the right to suspend or terminate your access if you violate these terms or abuse the system.
          </Typography>

          <Typography variant="h5" fontWeight="bold" gutterBottom>
            8. Changes to Terms
          </Typography>
          <Typography variant="body1" paragraph>
            We may update these terms periodically. We will notify users via email or on the website. Continued use
            after updates constitutes acceptance of the new terms.
          </Typography>

          <Typography variant="h5" fontWeight="bold" gutterBottom>
            9. Contact
          </Typography>
          <Typography variant="body1" paragraph>
            If you have questions or concerns, please contact us at: <strong>support@neuramedix.com</strong>.
          </Typography>
        </Container>
      </Box>
      <Footer />
    </>
  );
};

export default Terms;
